// Downloads the site's web fonts and writes the @font-face rules that point at the local
// copies. Run by hand; its output is committed.
//
// Self-hosting is not a preference here. The screenshot goldens are compared pixel for
// pixel, and a font that arrives from someone else's CDN — or does not arrive, and falls
// back to whatever the machine has installed — changes the metrics of every line on the
// page. It also keeps the site's own promise: hitbut loads nothing from a third party.
//
// Usage: node dev/tools/vendor-fonts.ts
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));
const FONT_DIR = path.join(REPO_ROOT, 'src/frontend/public/fonts');
const CSS_OUT = path.join(REPO_ROOT, 'src/frontend/src/fonts.GENERATED.css');
/**
 * The same two families as installable fonts, for the screen lane's font jail. The site
 * loads woff2 through CSS, which fontconfig cannot read — and a Chromium with no readable
 * font at all crashes its renderer, so the jail needs real files. Using our own families
 * means a glyph that does fall back still looks like the page.
 */
const FALLBACK_DIR = path.join(REPO_ROOT, 'dev/requirements/screen/fallback-fonts');
const FALLBACK_FONTS = [
  { file: 'FrankRuhlLibre.ttf', url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/frankruhllibre/FrankRuhlLibre%5Bwght%5D.ttf' },
  { file: 'Heebo.ttf', url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/heebo/Heebo%5Bwght%5D.ttf' },
];

/** Chrome's UA, so Google Fonts serves woff2 with variable weight ranges. */
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Frank Ruhl Libre', spec: 'Frank+Ruhl+Libre:wght@300..900', slug: 'frank-ruhl-libre' },
  { name: 'Heebo', spec: 'Heebo:wght@400..800', slug: 'heebo' },
];
/** Hebrew and Latin cover the corpus; a subset we do not ship is a glyph we cannot render. */
const SUBSETS = ['hebrew', 'latin', 'latin-ext'];

type Face = { subset: string; family: string; weight: string; unicodeRange: string; url: string };

function parseFaces(css: string): Face[] {
  const faces: Face[] = [];
  // Google Fonts labels each block with a `/* subset */` comment on the line before it.
  const blocks = css.split('/*').slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    if (!SUBSETS.includes(subset)) continue;
    const family = /font-family: '([^']+)'/.exec(block)?.[1];
    const weight = /font-weight: ([^;]+);/.exec(block)?.[1];
    const unicodeRange = /unicode-range: ([^;]+);/.exec(block)?.[1];
    const url = /src: url\(([^)]+)\)/.exec(block)?.[1];
    if (!family || !weight || !unicodeRange || !url) continue;
    faces.push({ subset, family, weight: weight.trim(), unicodeRange: unicodeRange.trim(), url });
  }
  return faces;
}

mkdirSync(FONT_DIR, { recursive: true });
const rules: string[] = [
  '/* GENERATED by dev/tools/vendor-fonts.ts — do not edit; change the generator and re-run. */',
];

for (const family of FAMILIES) {
  const response = await fetch(`https://fonts.googleapis.com/css2?family=${family.spec}&display=swap`, {
    headers: { 'user-agent': UA },
  });
  if (!response.ok) throw new Error(`${family.name}: the stylesheet answered ${response.status}`);
  const faces = parseFaces(await response.text());
  if (!faces.length) throw new Error(`${family.name}: no faces matched the subsets ${SUBSETS.join(', ')}`);

  for (const face of faces) {
    const file = `${family.slug}-${face.subset}.woff2`;
    const font = await fetch(face.url, { headers: { 'user-agent': UA } });
    if (!font.ok) throw new Error(`${file}: the font answered ${font.status}`);
    writeFileSync(path.join(FONT_DIR, file), Buffer.from(await font.arrayBuffer()));
    rules.push(
      '@font-face {',
      `  font-family: '${face.family}';`,
      '  font-style: normal;',
      `  font-weight: ${face.weight};`,
      '  font-display: block;',
      `  src: url('/fonts/${file}') format('woff2');`,
      `  unicode-range: ${face.unicodeRange};`,
      '}',
    );
    console.log(`vendored ${file} (${face.subset})`);
  }
}

mkdirSync(FALLBACK_DIR, { recursive: true });
for (const fallback of FALLBACK_FONTS) {
  const response = await fetch(fallback.url);
  if (!response.ok) throw new Error(`${fallback.file}: the font answered ${response.status}`);
  writeFileSync(path.join(FALLBACK_DIR, fallback.file), Buffer.from(await response.arrayBuffer()));
  console.log(`vendored ${fallback.file} (harness fallback)`);
}

mkdirSync(path.dirname(CSS_OUT), { recursive: true });
writeFileSync(CSS_OUT, `${rules.join('\n')}\n`);
console.log(`wrote ${path.relative(REPO_ROOT, CSS_OUT)}`);
