// The bulk export researchers read instead of paginating the whole corpus: one JSON
// object per line, regenerated by the scheduled run and served as a snapshot rather than
// assembled per request.
import type { R2Bucket } from '../env.ts';
import type { Corpus } from '../corpus/store.ts';
import { toWireStatement } from '../../shared/api.ts';

export const EXPORT_KEY = 'exports/statements.ndjson';

export async function generateStatementExport(corpus: Corpus, raw: R2Bucket): Promise<number> {
  const rows = await corpus.exportRows();
  const lines = rows.map((row) =>
    JSON.stringify({
      statement: toWireStatement(row.statement),
      figure: { id: row.figure.id, displayName: row.figure.displayName, role: row.figure.role },
      source: { id: row.source.id, url: row.source.url, publisher: row.source.publisher, kind: row.source.kind },
    }),
  );
  await raw.put(EXPORT_KEY, lines.length ? `${lines.join('\n')}\n` : '');
  return lines.length;
}
