// The bulk export researchers read instead of paginating the whole corpus: one JSON object
// per line, regenerated by the scheduled run and served as a snapshot rather than assembled
// per request.
//
// One line per **utterance**, with every document that reported it on the same line. A line
// per attestation would put one speech in the file five times and let a naive count of the
// export read the echo as five separate things said — the same failure the utterance split
// exists to prevent, arriving through the export.
import type { R2Bucket } from '../env.ts';
import type { Corpus } from '../corpus/store.ts';
import { toWireUtterance } from '../../shared/api.ts';

export const EXPORT_KEY = 'exports/utterances.ndjson';

export async function generateUtteranceExport(corpus: Corpus, raw: R2Bucket): Promise<number> {
  const lines: string[] = [];
  for (const utterance of await corpus.allUtterances()) {
    const figure = await corpus.getFigure(utterance.figureId);
    if (!figure) continue;

    const attestations = [];
    for (const attestation of await corpus.attestationsFor(utterance.id)) {
      const source = await corpus.getSource(attestation.sourceId);
      if (!source) continue;
      attestations.push({
        id: attestation.id,
        text: attestation.text,
        publishedAt: attestation.publishedAt,
        source: { id: source.id, url: source.url, publisher: source.publisher, kind: source.kind },
      });
    }

    lines.push(JSON.stringify({
      utterance: toWireUtterance(utterance),
      figure: { id: figure.id, displayName: figure.displayName, role: figure.role },
      attestations,
    }));
  }
  await raw.put(EXPORT_KEY, lines.length ? `${lines.join('\n')}\n` : '');
  return lines.length;
}
