// The site's own words, in the two languages the corpus is in. Direction and wording
// follow the *content*: an English pair renders an English page, left to right, because
// deferring non-Hebrew sources was never the plan — supporting both was.
import type { Language } from '../../shared/types.ts';

const he = {
  dir: 'rtl' as 'rtl' | 'ltr',
  brand: { stem: 'התבט', rest: 'אויות', latin: 'HITBUT' },
  nav: { search: 'חיפוש', methodology: 'איך זה עובד' },
  heroTitle: 'מה הם אמרו. מה הם אומרים עכשיו.',
  heroLede:
    'אוסף מתועד של התבטאויות פומביות, כל אחת עם המקור שממנו נלקחה — ובתוכו, המקומות שבהם הדברים לא מתיישבים זה עם זה.',
  searchPlaceholder: 'חיפוש בהתבטאויות…',
  searchAction: 'חיפוש',
  latest: 'סומנו לאחרונה',
  figures: 'דמויות במעקב',
  resultsFor: (query: string) => `תוצאות עבור «${query}»`,
  resultCount: (count: number) => (count === 1 ? 'התבטאות אחת' : `${count} התבטאויות`),
  noResults: 'לא נמצאו התבטאויות התואמות לחיפוש.',
  then: 'אז',
  now: 'עכשיו',
  but: 'אבל',
  whyFlagged: 'למה זה סומן',
  confidence: 'ודאות',
  viewSource: 'למקור',
  unknownDate: 'תאריך לא ידוע',
  context: 'הקשר',
  fullTimeline: 'לציר המלא',
  statements: 'התבטאויות',
  flagged: 'סומנו',
  topics: 'נושאים',
  kind: { anomaly: 'חריגה', 'trend-change': 'שינוי מגמה' },
  anomalyLede: 'ההתבטאות הזו רחוקה מהעמדה שהדמות מחזיקה בנושא הזה בדרך כלל.',
  // The sentence that matters most, on the page where the claim is made rather than one
  // click away on the methodology page.
  caveat: 'מודל שפה השווה בין ציטוטים שחילצנו ממקורות פומביים. הוא לא יודע מה הדובר התכוון, הוא לא רואה הקשר שלא נכתב, והוא יכול לטעות. הסימון הוא הזמנה לקרוא את הציטוטים ואת המקורות שלהם — לא מסקנה סופית.',
  caveatMore: 'מה עוד הסימון לא אומר',
  // No trailing space: Hebrew glues the prefix to the word after it.
  addressedTo: 'נאמר ב',
  audienceLabel: 'בפני\u00a0',
  venue: {
    plenary: 'מליאה', committee: 'ועדה', interview: 'ראיון', 'press-conference': 'מסיבת עיתונאים',
    'op-ed': 'טור דעה', broadcast: 'שידור', rally: 'עצרת', 'party-forum': 'פורום מפלגתי',
    'written-statement': 'הודעה בכתב', other: 'אחר',
  },
  audience: {
    'general-public': 'הציבור הרחב', parliament: 'הכנסת', 'party-members': 'חברי המפלגה',
    'foreign-press': 'העיתונות הזרה', professional: 'קהל מקצועי',
  },
  changedBetween: 'העמדה השתנתה בין',
  and: 'לבין',
  attestedBy: (count: number) => (count === 1 ? 'מקור אחד' : `${count} מקורות`),
  subject: 'נושא',
  unnamedSubject: 'נושא שטרם נקרא בשם',
  unplaced: 'ההתבטאות טרם שויכה לנושא.',
  utterances: 'התבטאויות',
  subjects: 'נושאים',
  supersededNotice: 'הסימון הזה הוחלף בסימון מאוחר יותר על אותו צמד. הוא נשמר כאן כי יש שהפנו אליו.',
  supersededLink: 'לסימון המעודכן',
  retired: 'הרשומה הזו הוסרה מהאתר ונשמרת כאן בלבד.',
  loading: 'טוען…',
  notFound: 'לא נמצא.',
  methodologyLink: 'איך האיתור עובד',
  coverageTitle: 'מה הרשומה הזו מכסה',
  coverageLede: 'מה שמופיע כאן נאסף מהמקורות האלה בלבד. דברים שנאמרו במקומות אחרים, או לפני התאריכים האלה, פשוט לא נאספו — היעדרם אינו אומר שלא נאמרו.',
  coverageFrom: 'מ־',
  coverageUnknown: 'טרם נרשם אילו מקורות מכסים את הדמות הזו.',
  rosterTitle: 'את מי אנחנו עוקבים, ולמה',
  rosterLede: 'זה המבחן שאנחנו מחילים, כתוב פעם אחת וחל על כולם:',
  rosterPer: 'ולכל דמות ברשימה — איך היא עומדת בו:',
  rosterEmpty: 'אין כרגע דמויות במעקב.',
  footerRights: 'התבטאויות — אוסף מתועד של אמירות פומביות.',
};

export type Strings = typeof he;

const en: Strings = {
  dir: 'ltr',
  brand: { stem: 'התבט', rest: 'אויות', latin: 'HITBUT' },
  nav: { search: 'Search', methodology: 'How this works' },
  heroTitle: 'What they said. What they are saying now.',
  heroLede:
    'A sourced record of public statements, each with the document it came from — and, inside it, the places where the record does not add up.',
  searchPlaceholder: 'Search statements…',
  searchAction: 'Search',
  latest: 'Recently flagged',
  figures: 'Figures tracked',
  resultsFor: (query: string) => `Results for “${query}”`,
  resultCount: (count: number) => (count === 1 ? '1 statement' : `${count} statements`),
  noResults: 'No statements matched that search.',
  then: 'Then',
  now: 'Now',
  but: 'but',
  whyFlagged: 'Why this was flagged',
  confidence: 'Confidence',
  viewSource: 'View source',
  unknownDate: 'Date not established',
  context: 'Context',
  fullTimeline: 'Full timeline',
  statements: 'statements',
  flagged: 'flagged',
  topics: 'topics',
  kind: { anomaly: 'anomaly', 'trend-change': 'trend change' },
  anomalyLede: 'This is far from the position this figure usually holds on this subject.',
  caveat: 'A language model compared quotes we extracted from public sources. It does not know what the speaker meant, it cannot see context that was never written down, and it can be wrong. A flag is an invitation to read the quotes and their sources — not a conclusion.',
  caveatMore: 'What else a flag does not say',
  addressedTo: 'Said at a\u00a0',
  audienceLabel: 'to\u00a0',
  venue: {
    plenary: 'plenary', committee: 'committee', interview: 'interview', 'press-conference': 'press conference',
    'op-ed': 'op-ed', broadcast: 'broadcast', rally: 'rally', 'party-forum': 'party forum',
    'written-statement': 'written statement', other: 'other',
  },
  audience: {
    'general-public': 'the general public', parliament: 'parliament', 'party-members': 'party members',
    'foreign-press': 'the foreign press', professional: 'a professional audience',
  },
  changedBetween: 'The position moved between',
  and: 'and',
  attestedBy: (count: number) => (count === 1 ? '1 source' : `${count} sources`),
  subject: 'Subject',
  unnamedSubject: 'an unnamed subject',
  unplaced: 'This utterance has not been assigned to a subject yet.',
  utterances: 'utterances',
  subjects: 'subjects',
  supersededNotice: 'This judgment was replaced by a later one about the same pair. It is kept because people linked to it.',
  supersededLink: 'The current judgment',
  retired: 'This record was withdrawn from the site and is kept here only.',
  loading: 'Loading…',
  notFound: 'Not found.',
  methodologyLink: 'How detection works',
  coverageTitle: 'What this record covers',
  coverageLede: 'What appears here was gathered from these sources only. Things said elsewhere, or before these dates, were simply not collected — their absence is not evidence they were not said.',
  // Non-breaking, so the label cannot end up flush against the date it precedes.
  coverageFrom: 'from\u00a0',
  coverageUnknown: 'Which sources cover this figure has not been recorded yet.',
  rosterTitle: 'Who we track, and why',
  rosterLede: 'This is the test we apply, written once and applying to everybody:',
  rosterPer: 'And for every figure on the roster, how they meet it:',
  rosterEmpty: 'No figures are being tracked.',
  footerRights: 'hitbut — a sourced record of public statements.',
};

export const STRINGS: Record<Language, Strings> = { he, en };

export const stringsFor = (language: Language): Strings => STRINGS[language];
